spring:
  application.name: kafcas-reactive-app

  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
    consumer:
      group-id: i-am-reactive-to-cas
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
      
  cassandra:
    schema-action: CREATE_IF_NOT_EXISTS
    request.timeout: 10s
    connection.connect-timeout: 10s
    connection.init-query-timeout: 10s

    local-datacenter: datacenter1
    keyspace-name: spring_cassandra