spring:
  application.name: kafcas-reactive-app

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: i-am-reactive
      
  r2dbc:
    url: r2dbc:postgresql://localhost/postgres
    username: postgres
    password: you
    initialization-mode: always      