spring:
  application.name: kafsql-app

  kafka:
    bootstrap-servers: localhost:9092
    listener:
      type: batch
    
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: you

  jpa:
    generate-ddl: true 
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect