spring:
  application.name: kafsql-app

  kafka:
    bootstrap-servers: localhost:9092
    
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testing
    username: root
    password: ANSKk08aPEDbFjDO

  jpa:
    generate-ddl: true 
    hibernate.ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect